version: '3.8'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
